apiVersion: apps/v1
kind: Deployment
metadata:
  name: donorapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: donorapi
  template:
    metadata:
      labels:
        component: donorapi
    spec:
      containers:
        - name: donorapi
          image: rushilojageer/donate-donorapi
          ports:
            - containerPort: 8002
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: SQL_CONNSTR_DONOR
              valueFrom:
                secretKeyRef:
                  name: sqlconnstrdonor
                  key: SQL_CONNSTR_DONOR
            - name: RMQ_HOSTNAME
              value: rabbitmq-cluster-ip-service
            - name: RMQ_USERNAME
              value: guest
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmqpassword
                  key: RMQ_PASSWORD
            - name: RMQ_PORT
              value: 5672