apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundworker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fundworker
  template:
    metadata:
      labels:
        component: fundworker
    spec:
      containers:
        - name: fundworker
          image: rushilojageer/donate-fundworker
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: SQL_CONNSTR_DONOR
              valueFrom:
                secretKeyRef:
                  name: sqlconnstrfund
                  key: SQL_CONNSTR_FUND
            - name: RMQ_HOSTNAME
              value: "rabbitmq-cluster-ip-service"
            - name: RMQ_USERNAME
              value: "guest"
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmqpassword
                  key: RMQ_PASSWORD
            - name: RMQ_PORT
              value: "5672"