apiVersion: v1
kind: Service
metadata:
  name: transactionprocessor-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: transactionprocessor
  ports:
    - port: 80
      targetPort: 80