apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionprocessor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: transactionprocessor
  template:
    metadata:
      labels:
        component: transactionprocessor
    spec:
      containers:
        - name: transactionprocessor
          image: rushilojageer/donate-transactionprocessor
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: SQL_CONNSTR_FUND
              valueFrom:
                secretKeyRef:
                  name: sqlconnstrfund
                  key: SQL_CONNSTR_FUND
            - name: RMQ_HOSTNAME
              value: rabbitmq-cluster-ip-service
            - name: RMQ_USERNAME
              value: guest
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmqpassword
                  key: RMQ_PASSWORD
            - name: RMQ_PORT
              value: 5672