// <auto-generated />
using System;
using Donate.CharityService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Donate.CharityService.API.Migrations
{
    [DbContext(typeof(CharityContext))]
    [Migration("20190922164322_CharityChanges")]
    partial class CharityChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Donate.CharityService.API.Data.Entities.Charity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CharityIdentifier");

                    b.Property<string>("CharityName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.HasIndex("CharityIdentifier")
                        .IsUnique();

                    b.ToTable("Charity");
                });
#pragma warning restore 612, 618
        }
    }
}
